### ISSUE TITLE
AuthGrabber 

### ISSUE THREAD

**Issue by fxdl02hog** [StanHutcheon/AuthGrabber#8]
So I configured an Ubuntu dektopr as a virtual host on win 2008 r2 and I get this message when I try to get the auth from a 4s phone:
./authGrabber.rb:40:in `unbind': undefined method`close' for nil:NilClass (NoMethodError)
    from /home/mine/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:1417:in `event_callback'
    from /home/mine/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/mine/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from ./authGrabber.rb:73:in`<main>'
Request cached, writing to auths/acehosts6.txt
./authGrabber.rb:40:in `unbind': undefined method`close' for nil:NilClass (NoMethodError)
    from /home/mine/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:1417:in `event_callback'
    from /home/mine/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/mine/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from ./authGrabber.rb:73:in`<main>'
Request cached, writing to auths/acehosts7.txt

I followed the instructions without error, and then I went in and changed the DNSMASQ.conf file to point to the local address of the ubuntu desktop by IP address. I tested this by performing a reverse lookup of quzzoni.apple.com from a different device on the network and it resolved back to the Ubuntu desktops IP.

I sent the cert from the AuthGrabber folder and installed it to the iPhone I was using. Then added to the network, changed the DNS server to the IP of the Ubuntu Desktop and tried Siri. The above message was received once for each press of SIRI, but all of the Auth files are empty?

Please advise how I can ffix this.

**Comment by dionysius** [comment]
+1 same here using CentOS 5.7. Exact same trace. Commenting authGrabber.rb line 40 did not help (after that ./cache.sh does nothing)

**Comment by dionysius** [comment]
I was able to fix it by rerunning ./certs.sh, emailing myself again and importing on 4s again - as suggested by a comment here http://thetecherra.com/2011/12/30/tutorial-make-your-own-siri-proxy-server-for-use-with-spire/#comment-407213733
I dunno what I did wrong, but this really fixed this issue
